### ISSUE TITLE
Integration with selectedpapers.net

### ISSUE THREAD

**Issue by mispy** [scirate/scirate#133]
Ideally two-way: comments from SciRate users show up on the selectedpapers site, and posts from Google+ or other places they harvest will appear in our comments sections.

Technologically, the simplest way to accomplish the former is most likely implementing an API on the selectedpapers site which allows us to do inter-server push notifications in a post-save handler for comments.

The inverse sync I am less certain about. It'd be nice to avoid having to maintain data format synchronicity; perhaps simply an embeddable widget which calls selectedpapers directly from the browser would be most appropriate.

Do we want to implement SciRate replies to selectedpapers comments, and if so, how would that look?

**Comment by silky** [comment]
this website doesn't even appear to exist anymore!
