### ISSUE TITLE
Categories take up too much space at top of screen on mobile 

### ISSUE THREAD

**Issue by sflammia** [scirate/scirate#171]
On small screens, the left-hand column comes strictly to the top and sits above the "scites" main column. This should be a hidden sidebar menu or something instead, I guess.

Is this coded in twitter bootstrap? Then there are classes that let you fix the responsiveness of the page to the display size built into the CSS.

**Comment by catch22** [comment]
It would also be great if the date picker stacked *above* the main column, rather than below. (Typical use case: trying to view yesterday’s papers on mobile.)

Thanks for all your hard work on scirate.

**Comment by marwahaha** [comment]
The datepicker is now moved above the main column. 
Let me think about categories.
