### ISSUE TITLE
data liberation

### ISSUE THREAD

**Issue by cosenal** [scirate/scirate#177]
It [would be great](https://support.google.com/accounts/answer/3024190?hl=en) if the user had a way to export his data (list of Scites and comments).
This doesn't necessarely mean the same data needs to be erased from the website once it's "liberated".

Three main use cases for this:
- import it into another service
- create his own copy for personal backup
- feel that data is not trapped trapped motivates more people to subscribe

Note this is different from #18 , which is about exporting the whole database.
### Implementation

**UI**: simply a button »Export« in the User Settings page
**data format**: to be decided, maybe json? I am not aware of other services that do something similar, but if they do exist, we should conform to what they do. Or maybe some format that is easy to convert to bibtex.

Note: I am willing to assign this issue to myself

**Comment by marwahaha** [comment]
related to https://github.com/scirate/scirate/issues/360

**Comment by marwahaha** [comment]
Downloading a user's scites is possible; i.e. https://scirate.com/ansis-rosmanis/download_scites

**Comment by marwahaha** [comment]
At this point, a user can:
* download their scites via json
* view all of their comments in html
both of these endpoints are paginated, so they should scale even if there is a lot of data.

In my opinion, the data is now completely available to the user. While it is not a one-click process, it is not obscured to the user nor trapped in the system. So I consider this issue addressed. If there is something missing please re-open this issue.
