### ISSUE TITLE
Summarize associated GitHub repos?

### ISSUE THREAD

**Issue by cgranade** [scirate/scirate#284]
To try and make source code for papers more visible, perhaps it would be good to detect GitHub (possibly also from other DVCS hosts) repositories linked to in arXiv comments and provide a brief summary below the paper? For instance, in our [benchmarking paper](https://scirate.com/arxiv/1404.5275), Chris Ferrie and I linked to a [GitHub repo](https://github.com/cgranade/accelerated-randomized-benchmarking) providing the full source code for the paper, such that it'd be cool to have that repo summarized on the SciRate page itself. Maybe a summary could include a list of included files, or a few lines from the README? Sorry if this Issue is a bit rough; it's not a fully-formed suggestion yet, though I think something along these lines could be very neat.

**Comment by marwahaha** [comment]
I think a compromise solution is the following:
1. Hyperlink links in author comments, so  SciRate users can click into the GitHub repos etc more easily. 
2. If the authors want to do something special advertising the repo, they can make a comment on their paper on SciRate. 

I worry that this is sort of a bespoke use, and "what to summarize" feels quite arbitrary so it will be hard to put in code. But if the authors have something they want to showcase they should feel compelled to make a comment on SciRate. In the meantime, authors can peruse links in the author comments at their own discretion.
