### ISSUE TITLE
live chat

### ISSUE THREAD

**Issue by silky** [scirate/scirate#292]
someone suggested that they don't like the permanency of comments on scirate.

what would people think of say having a live web chat, like the ones available on stackoverflow? as long as it supports MathJaX, it might be kind of nice.

thoughts?

**Comment by harrow** [comment]
My concern with this, and related ideas about private discussions, is that
they reduce the # of comments available to the commons.  Of course the
commenting rate is low in any case, so maybe we would not be losing much.

I don't have strong opinions either way.  What do others think?

aram

**Comment by silky** [comment]
the counter viewpoint is that it might increase the amount of comments available by creating a more enaged community. people may drop in for a chat which leads to some new insight or collaboration or whatever.

some questions would be: should we have channels? (say for arXiv category?) i'd guess probably not until the demand is great enough.

the reason i think it's cool is that it might be a nice way to grow the community, and have informal chats. but it might be hard to get it started, and we might need to have channels.

**Comment by andreabedini** [comment]
I'm not sure whether it is being developed anymore but there are easy drop-in solution for in-page chat system https://togetherjs.com/ not sure how to make it work with mathjax though (btw mathjax is horrible)

**Comment by silky** [comment]
what if we just had a slack channel?
