### ISSUE TITLE
paper missing from home feed and search

### ISSUE THREAD

**Issue by harrow** [scirate/scirate#293]
This paper
https://scirate.com/arxiv/1501.04944
does not show up here
https://scirate.com/?date=2015-01-21&range=1
or here
https://scirate.com/search?q=gosset_d

According to David Gosset, the paper was showing up for awhile (hence all the scites), and then disappeared.

**Comment by mispy** [comment]
we ran out of hdd space and had some issues for a bit, I think it's all fine now

**Comment by harrow** [comment]
Cool, thanks!

aram
