### ISSUE TITLE
where do the "report"s go?

### ISSUE THREAD

**Issue by silky** [scirate/scirate#296]
for example this comment - https://scirate.com/arxiv/0805.4018#433 - has been reported (by me, at least) and should clearly be deleted.

**Comment by mispy** [comment]
*checks* I'm not sure they go anywhere at the moment, except into the database. That clearly needs fixing.

**Comment by mispy** [comment]
Moderators/admins now have an option in their user settings to receive emails whenever a comment is reported (so they go to me and whoever else wants to opt in). I made Noon a moderator too
