### ISSUE TITLE
comments appear on recent comment list, but not post, when they've been deleted

### ISSUE THREAD

**Issue by silky** [scirate/scirate#303]
arams comment here - https://scirate.com/arxiv/1501.00008#458 - is not visible for me, but i see it on the recent comment list.

**Comment by harrow** [comment]
I clicked "hide from recent comments" for this one, so you won't see it
there any more, but this is still a bug.

**Comment by mispy** [comment]
Haven't had much luck reproducing this one. Any special circumstances or just a comment + delete from the same user?

**Comment by harrow** [comment]
I think it was comment + delete from the same user.  Did that not 
reproduce the problem when you tried it?

aram

**Comment by mispy** [comment]
I think I might have fixed this somewhere down the line. If it pops up again feel free to reopen
