### ISSUE TITLE
mechanism to handle anonymous comments

### ISSUE THREAD

**Issue by silky** [scirate/scirate#304]
maybe, instead of creating an anonymous account, there could be a way for existing users to post any given comment anonymously, if they wish. (i.e. a button "post anonymously".)

maybe this isn't a good idea, though, as we really should be encouraging openness?

**Comment by mispy** [comment]
Consensus in online communities has been that strong anonymity (i.e. completely nameless) rapidly promotes unkind behavior. Wonder if there's a research reference for that somewhere...

**Comment by silky** [comment]
fair enough

i guess i agree with you. it just seems a bit silly for  reviewers to be making anonymous accounts for each paper they want to review, which is what this issue was really about.

**Comment by mispy** [comment]
hmm, true. if people are doing it anyway we should probably find a way to accommodate that minimizes the potential harm

**Comment by mispy** [comment]
and if there's an "anonymous post" feature under an existing account then a moderator can trace it back if necessary

**Comment by silky** [comment]
> and if there's an "anonymous post" feature under an existing account then a moderator 
> can trace it back if necessary

yeah, that's what i was thinking. on the one hand it might actually not be appropriate for even moderators to know who the anonymous reviewers are, though, so ...

**Comment by eddieschoute** [comment]
I think it would be nice to have such a feature for posting questions about papers. It seems that currently the comment system remains somewhat underused.
Given that one can already make anonymous accounts at will, I'm not sure the unkind behavior quoted above would emerge that rapidly. But it may be good to have some moderator controls ready that do not necessarily reveal the identity of the anonymous commenter.
