### ISSUE TITLE
What is flash used for?

### ISSUE THREAD

**Issue by cosenal** [scirate/scirate#314]
Given the new security concerns about Adobe Flash, Firefox (version 39.0) asks me if I want to allow Flash on Scirate. What is it used for? Can't we just get rid of it?

**Comment by mispy** [comment]
It's used for the bibtex copy button, on account of web development being very strange. You should be able to safely disable it without breaking anything else

(github actually uses the same library for the repo clone url copy buttons)

**Comment by cosenal** [comment]
I see now, there is no non-flash alternative yet http://stackoverflow.com/q/10729570/825190 
Thanks for the quick answer.
