### ISSUE TITLE
Make time span viewed configurable

### ISSUE THREAD

**Issue by martinschwarz** [scirate/scirate#316]
I am refering to the time-span for which papers are
being displayed. If I'm loading the site without being logged in, it's set to "1 day",
which I prefer. Once I log in, it's set to "recent", which I'd like to change back
to "1 day", but don't know how. Can you please point my to where this can be
changed or change the hard-coded setting after log-in back to "1-day" please?

Especially on my mobile phone, it's a hassle to scroll through all the "recent"
papers (and stop before the comments) to find the button changing it back to
"1-day". It would be helpful, if the "1-day" button would be displayed on top
of the papers when viewed on a mobile device.

**Comment by silky** [comment]
you can change it per session by clicking here:

![thing](https://cloud.githubusercontent.com/assets/129525/8720574/d7d7a132-2bf6-11e5-950b-6f226a25fac6.jpg)

**Comment by martinschwarz** [comment]
Well, that was a trivial response. What I would like to have is
a per-user configurable default setting. As I wrote, I'd like to have a
sane default setting once I log in. It's OK ("1-day") if I'm logged
out, it's bad ("recent") once I log in for sciting. So my experience
is worse after logging in! I have also stated why: the exact switch
you are pointing to is a hassle to find on a mobile device (where
I'm checking new papers each day while commuting).

Maybe the frame with those switches can be moved atop, so it
is displayed as the first thing on low-resolution mobile screens?
That would be another improvement.

**Comment by mispy** [comment]
Time setting is now remembered cross-session. I would ideally like for "Recent" to be a useful default for most people-- it's meant to behave identically to 1d so long as you check the site each day. It can only know to do that if you're always logged in, though. hmm.

**Comment by martinschwarz** [comment]
Thanks as lot! Works now!
