### ISSUE TITLE
Suggestion:Create RSS feed from home feed

### ISSUE THREAD

**Issue by igor-krawczuk** [scirate/scirate#317]
Would be a nice way to browse the feed on the go as part of the news routine

**Comment by cosenal** [comment]
I am not sure this makes sense. You already have Arxiv's original RSS feed, and a Scirate's feed wouldn't add anything, as the number of Likes and the comments can change anytime. In order to make sense, your RSS reader would have to fetch the feed continuously and keep a notion of ordered feed.

**Comment by igor-krawczuk** [comment]
This can still be valuable, reddit and hackernews also generate their RSS feed whenever you reload...when I made the suggestion the main motivation was  mainly as an easy way to swap out the arxiv feed for the ordered scirate one.
