### ISSUE TITLE
handle arxiv-withdrawn papers somehow?

### ISSUE THREAD

**Issue by silky** [scirate/scirate#318]
consider - https://scirate.com/arxiv/1209.4152

the arxiv abstract has been updated and the paper no-longer exists

should scirate somehow also reflect this information?

**Comment by harrow** [comment]
I don't think our existing behavior is really a problem.  We link to the
arxiv pdf, which in this case is non-existent.  Unless there's some issue
with, say, a DMCA takedown request for something in an abstract (i.e.
something that we host), I think linking to retracted papers is fine. If
anything the fact that they were posted and then retracted is potentially
valuable information.

aram

**Comment by silky** [comment]
yes, i agree that keeping them on the site is a good idea; i was more referring to the fact that the abstract that arxiv displays is different to the one that scirate displays, so we could at least be in sync there.

**Comment by harrow** [comment]
Oh yeah, that does seem like a bug.

In general do we always list the v1 abstract?

aram

**Comment by marwahaha** [comment]
In recent withdrawn arXiv papers, the abstracts are left intact:
https://arxiv.org/search/?query=%22withdrawn+by+arXiv+administrators%22&searchtype=all&abstracts=show&order=-announced_date_first&size=50

**Comment by marwahaha** [comment]
I think this depends on the way the withdrawal happens. If it triggers an "updated paper announcement", then we update the  author comments -- see here for an example. 
* author comments update: https://scirate.com/arxiv/2304.04354 [v1](https://arxiv.org/abs/2304.04354v1), [v2](https://arxiv.org/abs/2304.04354v2)
I think we also update the abstract, but it's hard to find an example that is ALSO a withdrawal announcement.

On the other hand, sometimes the abstract is modified directly by arXiv admin possibly without an announcement. So it wouldn't be possible for scirate to know that it has been updated. An example:https://scirate.com/arxiv/2210.08982 [v1](https://arxiv.org/abs/2210.08982) there's not even a v2.

My guess for the original paper in question https://arxiv.org/abs/1209.4152 the paper was withdrawn with a comment (so we updated the comment), and then the abstract was modified directly (so we didn't update the abstract). Note that I have never seen a arXiv withdrawal without a comment. So I think the current behavior is fine.
