### ISSUE TITLE
Sidebar Comments and Markdown Rendering

### ISSUE THREAD

**Issue by Travis-S** [scirate/scirate#319]
In the "Recent Comments" sidebar, it looks like the Markdown text is rendered literally. For instance, writing a comment with a link to QInfer is rendered as

```
[QInfer](https://github.com/csferrie/python-qinfer)
```

Or, [this comment](https://scirate.com/arxiv/1509.04507#512) is displayed as 

```
Ha!&#13; &#13; For some background:&#13; &#13;
http://schroedingersrat.blogspot.fr/2014/07/letter-to-european-research-council.html
```

It would be nice if the comments interpreted the Markdown and displayed the comment as it would be seen on the article's scirate page.

**Comment by mispy** [comment]
Been meaning to fix this for a while, thanks for prodding :)
