### ISSUE TITLE
provide direct links on "comment on ..." papers

### ISSUE THREAD

**Issue by silky** [scirate/scirate#323]
maybe we could "thread" these papers; or at the very least have links between them all.

might be a nice way to track discussion.

inspired by:
- https://scirate.com/arxiv/1603.00825

one "feature" that might handle this would be to just automatically link any arXiv titles we find.

of course, we'd need to make sure when looking at the original you get links to the "Comment on ..." ones.

thoughts? is this or something like it a good idea? or not worth the effort?

if we like it, i'm happy to have a shot at it

**Comment by marwahaha** [comment]
#498 I think addresses this in a reasonable way; if they reference it with arXiv:blah in the abstract (which is how you get a arXiv hyperlink), then we use it to hyperlink to the reference's scirate page.
