### ISSUE TITLE
scirate code of conduct

### ISSUE THREAD

**Issue by silky** [scirate/scirate#324]
perhaps we could have a "code of conduct" that talks about what kinds of discussion we're interested in having on the site

i.e.:
- about the science
- constructive
- elaborating on points in the paper and further discussion

maybe this would help to eliminate talks about who should've referenced what? or is it too broad?

**Comment by harrow** [comment]
I actually don't think it's so bad to point out missing references.  I
don't think this Wilde thing was so bad, except for his hyperventilating
tone.

**Comment by silky** [comment]
alright.

my view is that it's not at all interesting to almost everyone on the site; or at least it's not at all interesting to me, what with being a bit outside academia. 

i'm happy to go with the majority view.

**Comment by cgranade** [comment]
Independent of the incident at hand, I think it is a worthwhile conversation to discuss codes of conduct. There's a lot of good advice out there for how to construct a useful code of conduct, too.

**Comment by harrow** [comment]
In this case, Wilde did talk about a lot of relevant history of who did
what.  That seemed pretty useful to at least the small subset of people
interested in this particular topic.  I will definitely be saving those
emails to look at if I ever have to referee some related paper.  But his
tone risked making everythign devolve into a flamewar.

Yeah, codes of conduct are a good idea.  We do have a moderation policy,
but maybe it's better to get users to agree to something.  of course many
of them have already created their accounts, but we could do ask them to
agree to the moderation policy going forward.

aram

**Comment by crazy4pi314** [comment]
I really like the idea that we adopt a code of conduct, here is a good example of one: http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy . For point of reference, here is a page with links to many codes of conduct adopted by other major tech companies/organizations/projects: http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations .

**Comment by mispy** [comment]
If we do have a longer code of conduct document, I would suggest:

- A short point summary on the signup page (please be respectful, etc)
- Another shorter one-line reminder to be nice + link on the comment form itself

**Comment by silky** [comment]
https://scirate.com/conduct
