### ISSUE TITLE
Search with custom time range

### ISSUE THREAD

**Issue by maxhgerlach** [scirate/scirate#327]
The search function in scirate is very useful to catch up on papers that appeared during some specific range in past time. I just noticed that the _lower_ bound on the date seems to be ignored, so that too many results are returned. [Example](https://scirate.com/search?advanced=in%3Acond-mat+date%3A2016-02-01..2016-03-11&page=2&q=monte+carlo&utf8=%E2%9C%93)

**Comment by marwahaha** [comment]
Checked a few cases. Looks like year parsing is ok, but not month or day parsing
https://scirate.com/search?utf8=%E2%9C%93&q=monte+carlo&advanced=au%3A%28Ronald+Fisch%29+in%3Acond-mat+date%3A2009..2010#results
