### ISSUE TITLE
Suggestion: add "sort by date" feature to the comments.

### ISSUE THREAD

**Issue by sflammia** [scirate/scirate#328]
The comment thread on this post shows that when threads are long it can get confusing if the good comments all just "bubble up" by getting votes, since sometimes there is not enough context to parse the meaning in isolation.
https://scirate.com/arxiv/1603.00825

**Comment by mispy** [comment]
Agreed, sorting by rating seems to introduce too much confusion. It's now date sorted by default. Replies to comments were already chronological but people don't always find the reply button.
