### ISSUE TITLE
Main site broken

### ISSUE THREAD

**Issue by marozols** [scirate/scirate#337]
The main SciRate site seems broken at the moment. It displays "We're sorry, but something went wrong." error message:
https://twitter.com/andrewmchilds/status/910136291546877952

To reproduce the issue, log yourself out and visit the main site. Alternatively, you can visit the main site using the "private mode" of your browser.

The problem does not occur if one is logged in. It also does not occur on sub-pages, such as  https://scirate.com/arxiv/quant-ph or pages for individual papers. In particular, one can log back in from any sub-page after which the main site works again.

**Comment by marozols** [comment]
As suggested by Henry Yuen, the issue might have to do with the new arXiv categories:
https://arxiv.org/help/eess/announcement

**Comment by silky** [comment]
thanks @marozols i'll look at this asap

**Comment by silky** [comment]
for the time being, people log in by going directly to https://scirate.com/login

**Comment by silky** [comment]
it's back now; after the latest scraping of papers today

so that's good news; i'll investigate the crash at some point.

thanks @marozols
