### ISSUE TITLE
recover better from arxiv outage

### ISSUE THREAD

**Issue by bentoner** [scirate/scirate#343]
From Anon via email to @dabacon :

There was an unusual situation with arXiv this week. Due to some outages on Monday night, no papers were posted. So two nights worth of papers appeared tonight. However, on Scirate only the papers from Monday night appeared. It appears that the papers that were supposed to appear tonight (including one by me) don't show up on Scirate at all. I'd at least like to notify whoever runs Scirate about this because it makes me rather sad.

**Comment by silky** [comment]
ah, okay, this makes sense; i _thought_ something weird happened.

i'll check it out

thanks @bentoner

**Comment by silky** [comment]
i guess what happened is that the sync ran, and just found nothing, but still recorded that it ran.

i guess i'll just need to prompt for the sync to run on that specific date. but i wonder how it will handle duplicates ...

**Comment by silky** [comment]
actually glancing at the code i think i might just be able to run the oai_import with a syncdate of sunday

it'll do a bunch of work importing papers it already has, but it should then only bring in the new papers and not dupe anything.

**Comment by harrow** [comment]
Do you think it's worth having the daily check look at the last week and import only the new ones?  Because periodically we miss a day for some reason, and that way it would recover automatically.

**Comment by silky** [comment]
let me see; i'll set up a dev environment on my computer and see how long it takes to do that query; if it's fast then it's not a bad idea, but if it's slow, maybe we could just make it a button on the admin side that is just run by one of us in a situation such as this.

**Comment by silky** [comment]
actually, @bentoner , do you have an example of a paper that was missed?

i can't find one. i assume this person is talking about tuesday

but there aren't _any_ entries for tuesday on arxiv - https://arxiv.org/list/quant-ph/recent

closing this issue until someone can point me to a paper that is missing ...

**Comment by bentoner** [comment]
(No I don't. @dabacon and I were just relaying information.)

**Comment by harrow** [comment]
@silky 
A paper that *was* missing is
https://scirate.com/arxiv/1711.04789
But now it's up.

**Comment by silky** [comment]
thanks @harrow 

@mispy is the best programmer; the code was already built to recover from this kind of failure! :)
