### ISSUE TITLE
incorporate papers from ChemRxiv

### ISSUE THREAD

**Issue by silky** [scirate/scirate#346]
they have an API, but not a bulk one - https://api.figshare.com/v2/articles

https://chemrxiv.org/f/faqs

https://docs.figshare.com/

https://editor.swagger.io/ ( for viewing swagger specs )

**Comment by silky** [comment]
in order to do this, we'd need to write a little bit of code similar to this - https://github.com/scirate/scirate/blob/master/lib/arxiv_import.rb


we'd also need to schedule the job to run at some point, and test that arXiv works well with multiple top-level things; we've not tried this so far.

**Comment by baoilleach** [comment]
+1

**Comment by mobeets** [comment]
+1, but also for biorxiv, medrxiv, psyarxiv, etc! For neuroscience for example, almost everyone publishes to biorxiv and not arxiv. So would be really cool if scirate could wrap around those as well!

Is it appropriate to change title of this issue to "*Rxiv"? Or does it depend case-by-case on how their api works I guess?

**Comment by mobeets** [comment]
Okay, so after trying to dig into what this would involve...In general, it looks like adding a new *rxiv to scirate would involve writing the equivalent of [arxivsync](https://github.com/mispy/arxivsync) for each *rxiv. Arxivsync assumes an OAI/xml api, which I believe is what biorxiv/medrxiv use, but you'd still need to tweak how to parse the (slightly different) metadata. Plus downstream I'm guessing you'd also need to make some assumptions about how to merge/combine the metadata fields from each *rxiv server's.

- For biorxiv/psyrxiv, I found a site [rxivist](https://rxivist.org/) that seems to do roughly what scirate does (but _only_ for biorxiv and medrxiv). They do also have an [api](https://rxivist.org/docs) btw.
- for psyrxiv, they don't seem to have an api at all

**Comment by silky** [comment]
thanks for talking a look! :)

interesting re: rxivist; i didn't know about it.

yes, the big difficulty is in writing the various scrapers.

i think, really, it would be good to just incorporate _any_ other one, because that would demonstrate the essential principle, and verify that the database structure works.

**Comment by mobeets** [comment]
Gotcha, yeah that makes sense!

And yeah for rxivist, I think it's just metadata + twitter/downloads metrics, so not actually any ability to comment or rate within the site.

**Comment by marwahaha** [comment]
consolidating issue in https://github.com/scirate/scirate/issues/499
