### ISSUE TITLE
show images from the papers above the paper abstracts, optionally

### ISSUE THREAD

**Issue by silky** [scirate/scirate#348]
this would be a very easy way to obtain information about how interesting the paper is at a quick glance

looks like the program `pdfimages` can extract some of the images, but it doesn't grab them all; i.e. it doesn't get tikz drawings, as far as i can tell from a 1-second attempt.

**Comment by silky** [comment]
i guess we could always do both

1. extract the regular images with `pdfimages`
2. extract the tikz sections by looking at the source (if it exists) and then rendering it somehow. perhaps via pandoc.

**Comment by silky** [comment]
unfortunately, i think this would be a bit of a drain on scirate/arxiv, as i'd need to download all the raw pdfs (and the source tex, if any, for the pandoc wackness), which is probably insane.

**Comment by harrow** [comment]
Yeah it did seem like a pretty challenging task.  Any this sort of summary is what the abstract is *supposed* to do, although it's true that in some fields the figures are really king.

**Comment by silky** [comment]
@harrow 

the extraction of raw images with `pdfimages` is actually trivial; it just worked immediately (i ran it on heaps of pdfs that I already had). just filtered out the ones < 15k and it gives a good sample.

the tikz sections via pandoc I think would also actually be pretty straightfoward

the only trouble is the bandwidth constraints. it does occur to me that arxiv-sanity ( http://www.arxiv-sanity.com/ ) seems to already get the pdfs to get it's screenshots.

*shrug*

it'd be really nice, but i don't want to strain the arXiv/SciRate server.
