### ISSUE TITLE
Suspected fake accounts

### ISSUE THREAD

**Issue by marozols** [scirate/scirate#359]
It seems that SciRate has become popular enough for people to start creating fake accounts to upvote their paper: [arXiv:1806.09569](https://scirate.com/arxiv/1806.09569#1168). Can anything be done to mitigate this?

**Comment by silky** [comment]
that's really odd.

i don't know what to do really. there's not enough info in the simple admin view to see if they're all from the same ip address

they have different email addresses though.

i'm not sure what to do

what are your thoughts?

**Comment by marozols** [comment]
In this case it seems fairly clear that these accounts are not genuine, so this kind of behavior backfires at the authors. Most people on SciRate are part of the community and they know who is behind which account (also, most people use their real names). But if SciRate keeps growing (and especially if it expands beyond quant-ph), this problem might become more serious.

**Comment by marozols** [comment]
Maybe you can add a text in the new account creation page discouraging people from creating anonymous accounts and suggesting they use their real name because an overwhelming majority of users on SciRate are part of the scientific community and know each other offline. You can also encourage new users to add a link to their homepage (or maybe even make this mandatory so it's easier to spot fake accounts). But I think it should still be possible to create anonymous accounts for legitimate reasons (e.g., [open peer review](https://scirate.com/perplexed-platypus).

**Comment by silky** [comment]
@marozols sounds pretty good to me; if you have time i'd really appreciate a pull-request adding something along those lines :)

**Comment by ryanlmann** [comment]
A similar thing occurred with https://scirate.com/arxiv/1805.10168 (take a look at the comments).

Accounts could require an existing user verify them, otherwise, is it possible to have Scirate accounts connected directly to an arXiv account? So that an arXiv account is required to create a scirate account, and could this still be done anonymously?

**Comment by alirezaseif** [comment]
How about requiring .edu email addresses for sign up?

**Comment by silky** [comment]
i don't want to limit scirate to arxiv accounts; i want it to be more open than that

@alirezaseif , for similar reasons i don't want to require edu addresses

one option would be just to be able to have people indicate that an account is spam by flagging it, and then the moderators can see the flags and perhaps trigger some further verification of the account. for example, we already have a way of marking an account as a spammer. maybe we could trigger some kind of email verification, and until that's confirmed, discount all the votes of those people?

this might be a nice task, if somewhat challenging, for someone who wants to start contributing more to the repo to get stuck into.

anyone want to take a shot at it?

**Comment by marozols** [comment]
@ryanlmann Indeed, it looks like the same kind of spam! Having existing users verify you would make it hard for other communities to adapt SciRate. There is currently an option to specify your [arXiv ID](https://arxiv.org/help/author_identifiers) which enables your arXiv papers to be displayed in your SciRate account. But again, making this mandatory would affect students who don't have papers yet.

@alirezaseif This would not cover institutions outside of US (I don't have an .edu address).

One simple countermeasure could be to disallow new users to upvote or comment for 24 hours. On the next day their paper would already be "old news" since it does not show on the main page, so it would be less appealing to go on and still try to rig the votes (also it would be more hassle because of the 24h delay). Perhaps this restriction can be removed if the user adds a website address or an arXiv ID to their profile.

@silky Yes, being able to flag suspicious accounts would also be helpful. I wish I spoke Ruby and could implement any of these ideas but unfortunately this is well beyond my current programming skills.

**Comment by silky** [comment]
we really need to do something about this

there's not so much fake upvoting at the moment; but there are thousands of fake accounts created each week.
