### ISSUE TITLE
'all time' sorting of articles by scites

### ISSUE THREAD

**Issue by vtomole** [scirate/scirate#364]
Maybe this already exists. It seems like the `Date Published` setting only goes back 1 year at most. I think it would be useful to increase it.

**Comment by silky** [comment]
you can use the custom date range

![image](https://user-images.githubusercontent.com/129525/59557746-101c7180-9025-11e9-8501-30791bf6b538.png)

**Comment by vtomole** [comment]
@silky Thank you.
