### ISSUE TITLE
paginate the list of users in the admin tab

### ISSUE THREAD

**Issue by silky** [scirate/scirate#368]
see https://github.com/scirate/scirate/commit/603a7cad0e9a64c3d81c2d064158e384bb80ed01 for the terrible hack to make the admin page load again.

it should be a straightforward task to make this page use the `will_pageinate` thing

**Comment by marwahaha** [comment]
<img width="1230" alt="Screenshot 2023-10-26 at 3 22 03 AM" src="https://github.com/scirate/scirate/assets/2541209/7431d9b5-699d-4e58-a0a7-ddec11c3494c">

works now!
