### ISSUE TITLE
scirate consistently failing to update

### ISSUE THREAD

**Issue by silky** [scirate/scirate#381]
it's now a serious problem.

**Comment by silky** [comment]
it's been reported twice; and it's happened at least 3-4 times in the last 2 weeks

i can jump on to the server and run it manually, and it works; so i'm not sure if something is timing out.

**Comment by silky** [comment]
this is now a serious issue

i have to manually run it every day :(

**Comment by silky** [comment]
spent a while looking into this; only thing i see is "getty" running at 100% - https://www.linode.com/community/questions/9916/100-cpu-by-getty#answer-73617 - but i don't think it's an actual problem

i've redirected the cron error emails to me ( they were going to mispy ) so we'll see if that leads to more info.

**Comment by silky** [comment]
i've had a good look into this now, and i still can't see what's happening

the update runs every hour

sometimes, the authorship sync fails because papers that should exist in scirate don't (this is probably worth understanding)

but i'm yet to see the paper update fail for totally unknown reasons

**Comment by silky** [comment]
i've been watching the cron logs for days now; and not seen anything go wrong

i'm going to go back to ignoring it, until someone tells me it's broken again

i don't understand at all why it wouldn't work ... :(

**Comment by silky** [comment]
okay

the issue is that the cron jobs stop running

**Comment by silky** [comment]
definitely not getting cron emails; and it baffles me as to why, as the cron service is running, evidentally.

**Comment by silky** [comment]
i don't know if it's related, but we're getting a lot of attempted access to scirate's postfix server :(

**Comment by silky** [comment]
for example, i see cron entires in the /var/log/syslog

`Aug 18 23:17:01 scirate CRON[23883]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)`

but i don't get emails, and i see all these postfix errors

:shrug:

**Comment by silky** [comment]
well, now hopefully there's significantly less noise around mail ( https://github.com/scirate/scirate/issues/383 ); let's see what happens

**Comment by silky** [comment]
well, i can see definitely that the cron job is running, but also definitely i'm not receiving any emails, and it evidently fails.

**Comment by silky** [comment]
ah!

it's because it's using flock; and the lock file is still open; i believe because a `paper_sync` is _still running_ from aug 17th; so it's blocking everything subsequently ....

the question now is ... why?

**Comment by silky** [comment]
i've added some stuff to hopefully capture some output in a log `log-sync.txt` in the home directory

**Comment by silky** [comment]
ultimately it's clear that the problem is that this script hangs

but i don't know why

**Comment by johannesjmeyer** [comment]
I know I'm just chipping in here randomly without much knowledge of the codebase, but could you try killing the old job when flock refuses to start and then run the new sync?

**Comment by silky** [comment]
thanks for jumping in@johannesjmeyer !

yeah; that's probably a good idea as a solution

my concern is that maybe if the job takes more than an hour, then it'll just do that repeatedly?

and i guess i'm moderately interested in the actual reason for the failure

but yes, maybe you're right, and i should just put that in and continue logging stuff anyway, and at least it should be functional ...

**Comment by johannesjmeyer** [comment]
I think if only some of the jobs fail then killing the process will at least more or less make the site work. Btw, if the job is cancelled, does it roll back everything it already synced? 

Another idea is to maybe make the interval between syncs a bit longer.

**Comment by silky** [comment]
nah; the job can definitely be killed and resumed

the thing that takes a long time is the author sync

it's not that i'm worried so much about interrupting it; i'm more worried about missing an important problem by not understanding why it freezes; i'd like to know the underlying cause

**Comment by jon-2124** [comment]
This is now a daily occurrence, Scirate either does not update or updates extremely late (sometimes more than a day late).

**Comment by silky** [comment]
frustrating, isn't it.

**Comment by silky** [comment]
it updates late because i have to do it manually :)

**Comment by silky** [comment]
this issue just needs some love. i'm not going to have time to look into it until christmas.

**Comment by jon-2124** [comment]
@silky I see, I didn't know that you were updating it manually. I hope that someone in the community can help! Thanks for your work on this, the site is very useful and I hope that the issues get fixed soon.

**Comment by silky** [comment]
i'm ambitiously going to claim this is fixed

i changed the sync script to be this:

```
RAILS_ENV=production bundle exec rake arxiv:paper_sync
RAILS_ENV=production bundle exec rake arxiv:author_sync
```

so now it doesn't do any of the OOM stuff

i'll bring that back if it's an issue
