### ISSUE TITLE
only allow logged-in users to search

### ISSUE THREAD

**Issue by silky** [scirate/scirate#384]
there seems to be a lot of spam generated by random hacking attempts via the search bar

i don't think search is so crucial that logged-out users need it; so maybe a very simple fix is just to only allow searching when logged in?

**Comment by silky** [comment]
i've had a request to bring this back; so i'll probably do that tomorrow.

**Comment by JacksonBates** [comment]
What was the nature of the spam generated by the search bar? Just logs or something else?

**Comment by silky** [comment]
just random hacking attempts, which generates heaps of emails which is annoying to read through

i can't find any right now though

**Comment by JacksonBates** [comment]
Might be able to use reCaptcha on the field...v3 is pretty flexible I think

**Comment by silky** [comment]
mm that's a good idea; i like it! are you happy to give it a go?

**Comment by JacksonBates** [comment]
Yeah, if I don't pass out early I'll take a look tonight.

**Comment by JacksonBates** [comment]
Hmm, I think this won't work as the search is a GET request instead of POST.

**Comment by silky** [comment]
yeah okay, no worries

i'm happy to close it if you are?
