### ISSUE TITLE
Some readme discrepancies / outdated parts

### ISSUE THREAD

**Issue by JacksonBates** [scirate/scirate#386]
Following the README there were some discrepancies I had to work around to get everything up and running.

I'm happy to either amend the README or add my notes as separate gotchas - but maybe someone else would like to verify these issues on a clean box first?

OS: Ubuntu 18.04

## RVM
RVM installation instructions failed - something to do with the GPG keys, I think.
Following the Digital Ocean version worked: https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-18-04

## openjdk-6-jre
apt reports there are no installation candidates for this. I had to `sudo apt-get install openjdk-8-jre` for this to work

### capybara
`gem install capybara-webkit -v 1.5.1` failed with `command qmake not available`
OS specific solutions here: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#debian--ubuntu

This is what worked for me:
```
sudo apt-get update
sudo apt-get install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
```
Then the gem install works
### postgres
`gem install pg -v 0.18.2` failed with `Can't find the 'libpq-fe.h header`

OS specific solutions here: https://stackoverflow.com/a/6040822/12848423
For me:
```
sudo apt-get install libpq-dev    
```
Then gem install works.

## Elasticsearch and the rake es:migrate task
This was a curly one...I went down some rabbit holes trying to fix this, and the ultimate solution may have just been me restarting my computer.

The readme suggests using `sudo service elasticsearch start` to run the service, but that doesn't work for me. Instead I run the elastic from the relevant /bin directory.

**Comment by silky** [comment]
@JacksonBates thanks for this!

i think just updated the readme with what worked for you with ubuntu; it's our dev and deployment environment anyway, and i think people on other platforms can work it out from those instructions

thanks! :+1:
