### ISSUE TITLE
prevent searching via the url when not logged in

### ISSUE THREAD

**Issue by silky** [scirate/scirate#390]
related to https://github.com/scirate/scirate/issues/384 - maybe we could also just redirect to the homepage if a search is attempted when a user isn't logged in

should be a change to `app/controllers/papers_controller.rb`; probably just adding a check for `if not current_user` then redirecting if there isn't one.

a good test for this is that the following link:

- https://scirate.com/search?utf8=%E2%9C%93&q=abc

should work when logged in, but redirect home when logged out.

**Comment by jonathanyeong** [comment]
Hey there! I was referred here by @JacksonBates. Could I take this issue?

**Comment by silky** [comment]
hey @jonathanyeong, welcome! that would be awesome, thank you! :)
