### ISSUE TITLE
Travis build broken (for a year)

### ISSUE THREAD

**Issue by JacksonBates** [scirate/scirate#392]
It looks like the CI/CD has been broken for about a year.

Builds all seem to error out with:

`The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .`

See: https://travis-ci.org/github/scirate/scirate/pull_requests for all of them

**Comment by silky** [comment]
yeah; this is a bit mystifying. i'll have a go at trying to fix this. thanks!

**Comment by silky** [comment]
i've gotten it to the point that it seems to be failing due to elasticsearch not running ... interesting.

**Comment by silky** [comment]
okay; it's just because the elasticsearch service doesn't start when it's installed via that fashion

i was going to go down the rabbit hole of fixing this; but i think the best bet is just to upgrade elasticsearch; this should solve a bunch of problems. i'll tie this ticket to that

#354
