### ISSUE TITLE
Bug: paper not showing on profile

### ISSUE THREAD

**Issue by dding7293** [scirate/scirate#399]
I wanted to reach out about a possible bug in Scirate. I released a paper last week on arXiv (2011.10564) but it didn't show up on my Scirate page. My scirate ID is dawei-ding and my arXiv author identifier is ding_d_1.

**Comment by silky** [comment]
thanks for reporting this issue @dding7293 

this is something i'll have to look into; i haven't looked into this aspect of scirate very much

**Comment by hillmich** [comment]
I encountered the same problem, my latest paper from [arxiv](https://arxiv.org/a/hillmich_s_1.html) is missing on my [Scirate profile](https://scirate.com/hillmich/papers).

Unfortunately, I have no experience in Ruby / Rails but I thought a second case of the bug might be helpful.

**Comment by silky** [comment]
thanks; there's now a third instance of this; so certainly something i'll investigate soon :)

**Comment by silky** [comment]
these are both fixed; it's actually all related to #381 ; when the update fails the authorship has been failing to update.

thanks for reporting these!
