### ISSUE TITLE
Erroneous "12" in paper abstract?

### ISSUE THREAD

**Issue by ampolloreno** [scirate/scirate#414]
It looks like there is an extra "12" at the end of [this abstract](https://scirate.com/arxiv/2102.06693) - I'm not sure why.

**Comment by ampolloreno** [comment]
![Screenshot from 2021-02-14 21-40-41](https://user-images.githubusercontent.com/15059859/107906016-5ec29300-6f0d-11eb-86a8-3e6dd97c7414.png)
Browser is Firefox on Ubuntu 20.04.1 LTS.

**Comment by silky** [comment]
it's in the abstract itself :) you can see this on the arxiv - https://arxiv.org/abs/2102.06693

**Comment by ampolloreno** [comment]
Oh shoot - I had only looked at pdf!
