### ISSUE TITLE
add letsencrypt renew to cron jobs

### ISSUE THREAD

**Issue by silky** [scirate/scirate#425]
i think it's as simple as `sudo certbot renew`

but, note that the webserver needs to be restarted for the fix to take place; but i think this will happen naturally due to the weekly restart

**Comment by JacksonBates** [comment]
I did this for a couple of sites at work - it's pretty easy. You're right, sudo certbot renew is all you need. I don't recall having to restart the webserver, but I could be wrong.

The only complication I ran into is that one of our servers was the Amazon Linux flavour of EC2 and that needs a whole bunch of dependencies installed. If you're just running Ubuntu, it's easy.

**Comment by marwahaha** [comment]
I think this is already happening, but we can see if the certificate updates in a few days (systemd runs twice a day, should update expiration is within 30 days):
```
root@scirate:/home/scirate# certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: scirate.com
    Domains: scirate.com www.scirate.com
    Expiry Date: 2022-06-09 01:05:57+00:00 (VALID: 33 days)
    Certificate Path: /etc/letsencrypt/live/scirate.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/scirate.com/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by marwahaha** [comment]
This is working.
