### ISSUE TITLE
make a twitter/discord bot that posts the top papers each day

### ISSUE THREAD

**Issue by silky** [scirate/scirate#430]
steps:

1. make an rss feed with the top 10 papers, say
2. maybe filtered by category ("quant-ph", etc)
3. somehow link this to a discord bot ( i have no idea how! )
4. ???
5. profit!

i believe people in the "unitary hack" discord would be interested in this

**Comment by harrow** [comment]
Great idea!  How about twitter?  The only issue is that there should be a lag to give people time to get all their scites in.  Do you think a 1-day lag would be good?

**Comment by infiniteregrets** [comment]
Hey, so I made the discord bot. Not sure where to submit my code. Let me know! Also, this is just a basic layout of the bot, I can add more features as you say. 
![Screen Shot 2021-05-19 at 2 30 35 AM](https://user-images.githubusercontent.com/65443164/118723952-a548c600-b84b-11eb-88b8-997e268355e3.png)

**Comment by silky** [comment]
hey @infiniteregrets - this is great!

Forgive me ignorance, but what does the code look like?

I think, depending on that, the most sensible idea would be for me to make a new repository on the `scirate` organisation and we host it there.

**Comment by infiniteregrets** [comment]
This was barely 50 lines of code, depending on your requirements I can add more features. Should I upload the code to my account and share the link? If you want I can make a Twitter bot too

**Comment by infiniteregrets** [comment]
Also, I can do that Docker thing too? But is it a part of unitary hack? or is it just the nix thing? I havent studied much about nix, but I can take a look

**Comment by silky** [comment]
i've made a repo here - https://github.com/scirate/scirate-bots - if you can fork that and push the code for the discord bot part, along with some instructions/readme, I'll take a look :)

The part I'm wondering is if we should make an api endpoint within SciRate that makes it easier to capture the top papers.

**Comment by silky** [comment]
@infiniteregrets certainly the nix setup task is part of unitaryhack; would very much appreciate you taking a look at that! :)

**Comment by infiniteregrets** [comment]
@silky done, check it

**Comment by silky** [comment]
fixed by https://github.com/scirate/scirate-bots/pull/1 ! 

thanks @infiniteregrets !
