### ISSUE TITLE
database backups are failing because of a version mismatch

### ISSUE THREAD

**Issue by silky** [scirate/scirate#457]

**Comment by silky** [comment]
pg_dump: server version: 9.5.24; pg_dump version: 9.3.24
pg_dump: aborting because of server version mismatch

**Comment by silky** [comment]
actually, i don't know why they are failing; but running them manually works:

```
pg_dump -Fc --no-acl --no-owner scirate_live > ~/scirate_live.dump
```

**Comment by marwahaha** [comment]
It seems like the backups are being taken properly, but there's mail messages that they aren't. For example, with the terminal, it looks like the server version is 9.3.25. 

I'm wondering if this is an artifact of all the cron jobs running at the same time. I've staggered them and hope it helps.

**Comment by marwahaha** [comment]
The answer is that the postgres running `scirate_live` (scirate/scirate) is 9.3, but the postgres running `scirate_jobs_live` (scirate/scirate-jobs) is 9.5. So that backup doesn't work. Using `/usr/lib/postgresql/9.5/bin/pg_dump` will probably fix it.

**Comment by silky** [comment]
note you can probably just completely remove the scirate-jobs stuff (unless you plan on re-instating it).
