### ISSUE TITLE
missing papers?

### ISSUE THREAD

**Issue by sflammia** [scirate/scirate#480]
There seem to be some papers missing today, which makes me worry that there are more papers missing in general. The paper that I don't see listed is this one: [2306.14887](https://arxiv.org/abs/2306.14887). I don't know what might have caused this or if there are others that were also missed in this update.

**Comment by marwahaha** [comment]
I think this was caused by an arXiv delay. Looking into it now.

**Comment by marwahaha** [comment]
This was an arXiv API issue sending incomplete data. I submitted a bug report which they fixed the next day, and it seems like we have all papers again.
