### ISSUE TITLE
Banner about confirmation email not going away

### ISSUE THREAD

**Issue by gregrosent** [scirate/scirate#483]
I recently created an account and at the top it says "Welcome to SciRate! A confirmation message was sent to [email address]." However the confirmation message wasn't sent, and there's no way to make the banner go away besides logging out. Clicking "Resend Confirmation" doesn't actually resend the confirmation (or make the banner disappear).

**Comment by marwahaha** [comment]
Sorry about that, that sounds frustrating. Did you make an account with Google or with your email address?

**Comment by gregrosent** [comment]
I don't remember for sure, but I think it was with my email address.

**Comment by marwahaha** [comment]
Okay, thanks for letting me know.

I'm leaving a suspicious warning I noticed in the test environment:
> ..DEPRECATION WARNING: Sending mail with DeliveryJob and Parameterized::DeliveryJob is deprecated and will be removed in Rails 6.2. Please use MailDeliveryJob instead. (called from block (2 levels) in <class:CommentReport> at /app/app/models/comment_report.rb:22)

**Comment by marwahaha** [comment]
Hi @gregrosent , could you try clicking "Resend Confirmation" again and let me know if the email goes through?

**Comment by gregrosent** [comment]
It works now and the banner's gone - thanks!
