### ISSUE TITLE
mail from linux server is broken

### ISSUE THREAD

**Issue by marwahaha** [scirate/scirate#494]
I think the outgoing mail has been broken since possibly August 2022. The postfix server is not authenticated with SPF nor DKIM.

**Comment by marwahaha** [comment]
probably related to #483

**Comment by marwahaha** [comment]
@silky could you explain how the mail system was set up? there was a sendgrid account? I think everyone here has forgotten how that worked.

**Comment by silky** [comment]
as i recall yes there was a sendgrid account somewhere; account details are ( i believe ) in the secrets file on the server somewhere.

if i remember well, i think if you have everything set up locally you can test that it sends emails

here's the config - https://github.com/scirate/scirate/blob/main/config/initializers/action_mailer.rb#L10

_maybe_ sendgrid expired; probably someone had to be paying it; maybe @harrow  was doing that?

**Comment by marwahaha** [comment]
This is what I understand.

* The scirate app uses sendgrid to send user emails like "reset password" and "activate account". This is failing according to the production logs. Regardless, we're going to update it with my new sendgrid account. We're on the free tier, that's fine.
* to set up the new sendgrid account, we have to add some DNS records. The DNS records are currently managed with DigitalOcean right now, but we can just put the DNS records with Google Domains.
* Once we add the DNS records, it seems like email will just work again (and we can stop deleting the production logs every week, that was a weird idea...)

Separately, when the crontab runs, it sometimes errors, which sends email using (I think) the linux command `mail` . This is the outgoing email that is getting blocked because of SPF/DKIM. I'm not sure exactly what to do about this, but if the crons fail it would be nice to know somehow.

**Comment by marwahaha** [comment]
Ok, I moved DNS back to google domains. The sendgrid emails are now working I think.  Let's verify in #483 

The cron emails are still broken, let's fix that here.

**Comment by marwahaha** [comment]
I followed this tutorial: https://docs.sendgrid.com/for-developers/sending-email/postfix

Then I made a fake crontab that errored out, and the email came through! 😄
