### ISSUE TITLE
Missing papers?

### ISSUE THREAD

**Issue by eurekash** [scirate/scirate#500]
Some papers on today (10/26) are missing, e.g., https://arxiv.org/abs/2310.16155.

**Comment by marwahaha** [comment]
Hi, this is unfortunate. Do you have a sense of how many papers are missing?
We use this API to process new data from arXiv, but I don't see the paper you linked in any of these URLs.
Lately though arXiv has taken awhile to update these endpoints. If you have another example of a missing paper, I'll file a ticket against them (the third in recent memory).

http://export.arxiv.org/oai2?verb=ListRecords&from=2023-10-24&metadataPrefix=arXivRaw
http://export.arxiv.org/oai2?verb=ListRecords&resumptionToken=6825723|1001
http://export.arxiv.org/oai2?verb=ListRecords&resumptionToken=6825723|2001
http://export.arxiv.org/oai2?verb=ListRecords&resumptionToken=6825723|3001
http://export.arxiv.org/oai2?verb=ListRecords&resumptionToken=6825723|4001
http://export.arxiv.org/oai2?verb=ListRecords&resumptionToken=6825723|5001

**Comment by marwahaha** [comment]
glancing at the output of the API, it looks like URLs between 2310.16116 and 2310.16350 did not get included in the API. I'll file a bug against arXiv (at this link https://arxiv-org.atlassian.net/servicedesk/customer/portal/1/group/1/create/1)

**Comment by eurekash** [comment]
Looks like these papers are imported today. Thanks!

**Comment by marwahaha** [comment]
Oh great! In the future if this happens feel free to make another issue and I'll investigate. I had to file a ticket against arXiv (which they responded and re-indexed the OAI2 API) and scirate picked up the papers. But I think if we don't make arXiv fix it by the next paper release then scirate will miss the papers.
