### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by eurekash** [scirate/scirate#511]
Papers 2311.03307 is missing. It looks like all papers after 2311.03300 are not showing up as well.

**Comment by eurekash** [comment]
2311.03307

**Comment by marwahaha** [comment]
Thanks, I'll take a look.

**Comment by marwahaha** [comment]
Usual suspect -- our upstream API  (from arXiv) doesn't have papers above 2311.03300 . I'll send a bug report to them (must be the fourth or fifth time now!)

**Comment by marwahaha** [comment]
Sent a bug report to arXiv, I expressed my frustration more strongly this time. Ideally it will be there tonight. Sorry about this.

**Comment by eurekash** [comment]
Thanks very much！

**Comment by marwahaha** [comment]
Looks fixed now.
