### ISSUE TITLE
Autolink identifiers of the form "arXiv:math/0612849" in abstracts and comments

### ISSUE THREAD

**Issue by ghost** [scirate/scirate#95]

**Comment by silky** [comment]
i.e. these should link to the appropriate page on scirate

**Comment by marwahaha** [comment]
I think they should instead link to arXiv.

**Comment by marwahaha** [comment]
I was a little hasty. #495 broke the Scite functionality! So I reverted it.

**Comment by silky** [comment]
great to see you working on this one! :)

i know it's not my decision anymore, but i would really vote strongly to link to scirate; i think one benefit of this feature is you often see that link and think "oh, i didn't know about that paper, i want to save that one too"; so this saves you the round trip

and, scirate links to arxiv, but arxiv doesn't like to scirate :D

**Comment by marwahaha** [comment]
Sure, that's okay with me. I hate the semantic scholar buttons below arxiv because they take you to semanticscholar's website when I just want to traverse references. But the jarring part I guess is that I'm on arXiv and I end up somewhere else. By that logic, linking to scirate is actually better.
